version: "3"

services:
  app:
    container_name: integrator
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - ${CONTAINER_PORT:-3030}:${HOST_PORT:-3030}
    command: ["-c", "knex migrate:latest && knex seed:run && npm start"]
    entrypoint: ["/bin/sh"]
    environment:
      - DOJOT_ENDPOINT=dojot
      - DOJOT_USERNAME=admin
      - DOJOT_PASSWORD=admin
      - MYSQL_DB_USER=root
      - PLATIAGRO_ENDPOINT=platiagro
      - SERVER_PORT=3030
      - SERVER_KEY="bf06c9e3-78d3-422b-8a1e-6f3909add993"
      - APP_PORT=3333

  db:
    container_name: "${DB_HOST:-mysql}"
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-integrator}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
