name: Node.js CI

on: 
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Set Docker TAG
      id: var
      run: |
        echo ${{ github.ref }}
        if [ ${{ github.ref }} = "refs/heads/master" ]; then
          echo ::set-output name=TAG::0.1.0
        else
          echo ::set-output name=TAG::0.1.0-SNAPSHOT
        fi
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
    - name: Build and push image
      if: ${{ always() }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/dojot-integration
        tags: ${{ steps.var.outputs.TAG }}